SWP391.OnlineShop.Portal/Controllers/ElementController.cs
using Microsoft.AspNetCore.Mvc;

namespace SWP391.OnlineShop.Portal.Controllers
{
    public class ElementController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SWP391.OnlineShop.Portal/Controllers/PostController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ServiceStack;
using SWP391.OnlineShop.Core.Models.Identities;
using SWP391.OnlineShop.ServiceInterface.Loggers;
using SWP391.OnlineShop.ServiceModel.ServiceModels;
using SWP391.OnlineShop.ServiceModel.ViewModels.Products;

namespace SWP391.OnlineShop.Portal.Controllers
{
    public class PostController : BaseController
    {
        private readonly IJsonServiceClient _client;
        private readonly ILoggerService _logger;
        private readonly UserManager<User> _userManager;
        public PostController(IJsonServiceClient client,
           ILoggerService logger,
           UserManager<User> userManager)
        {
            _client = client;
            _logger = logger;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index(string search, int categoryId, int tagId, int page = 1)
        {
            var posts = new List<PostViewModel>();
            if (!string.IsNullOrEmpty(search) && categoryId == 0 && tagId == 0)
            {
                posts = await _client.GetAsync(new GetPostByTitle
                {
                    Title = search
                });
            } else if (string.IsNullOrEmpty(search) && categoryId != 0 && tagId == 0)
            {
                posts = await _client.GetAsync(new GetPostByCategory
                {
                    CategoryId = categoryId
                });

            } else if (string.IsNullOrEmpty(search) && categoryId == 0 && tagId != 0)
            {
                posts = await _client.GetAsync(new GetPostByTag
                {
                    TagId = tagId
                });
            } else
            {
                //get all post
                posts = await _client.GetAsync(new GetAllPost());
            }

            ViewBag.Pages = posts.Count % 5 == 0 ? posts.Count / 5 : posts.Count / 5 + 1;
            ViewBag.CurrentPage = page;

            posts = posts.Skip((page - 1) * 5).Take(5).ToList();
            foreach (var post in posts)
            {
            //get tag by post
                var tags = await _client.GetAsync(new GetTagByPost()
                {
                    PostId = post.Id
                });
                post.Tags = tags;
            }
            
            //get all tag
            ViewData["AllTags"] = await _client.GetAsync(new GetAllTag());
            return View(posts);
        }

        public async Task<IActionResult> Details(int id)
        {

        //get post by id
            var post = await _client.GetAsync(new GetPostById()
            {
                PostId = id
            });
        //get tag by post
            var tags = await _client.GetAsync(new GetTagByPost()
            {
                PostId = post.Id
            });
            post.Tags = tags;
        // get all tag
            ViewData["AllTags"] = await _client.GetAsync(new GetAllTag());
            return View(post);
        }
    }
}

SWP391.OnlineShop.Portal/Controllers/ProductController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ServiceStack;
using SWP391.OnlineShop.Core.Models.Identities;
using SWP391.OnlineShop.ServiceInterface.Loggers;
using SWP391.OnlineShop.ServiceModel.ServiceModels;
using SWP391.OnlineShop.ServiceModel.ViewModels.Products;
using System.Security.Claims;

namespace SWP391.OnlineShop.Portal.Controllers
{
	public class ProductController : BaseController
	{
		private readonly IJsonServiceClient _client;
		private readonly ILoggerService _logger;
		private readonly UserManager<User> _userManager;
		public ProductController(IJsonServiceClient client,
		   ILoggerService logger,
		   UserManager<User> userManager)
		{
			_client = client;
			_logger = logger;
			_userManager = userManager;
		}

		public async Task<IActionResult> Index(int categoryId, int tagId, int page = 1)
		{
			List<ProductViewModel> latestProducts = new List<ProductViewModel>();
			if (categoryId != 0 && tagId == 0)
			{
				//Get all products by categoryId
				latestProducts = await _client.GetAsync(new GetProductByCategoryId
				{
					CategoryId = categoryId
				});
			}
			else if (categoryId == 0 && tagId != 0)
			{
				latestProducts = await _client.GetAsync(new GetProductByTagId
				{
					TagId = tagId
				});
			}
			else
			{
				//Get all active products
				latestProducts = await _client.GetAsync(new GetAllActiveProduct());
			}

			ViewBag.Pages = latestProducts.Count / 9 + 1;
			ViewBag.CurrentPage = page;

			//Get all categories
			var categories = await _client.GetAsync(new GetAllCategory());

			//Get deal product of week
			var dealProductOfWeeks = await _client.GetAsync(new GetDealProductOfWeek());

			var tags = await _client.GetAsync(new GetAllProductTag());

			var productCategories = new ProductCategoryViewModel
			{
				LatestProducts = latestProducts.Skip((page - 1) * 9).Take(9).ToList(),
				Categories = categories,
				ProductsOfWeek = dealProductOfWeeks,
				Tags = tags
			};
			return View(productCategories);
		}

		public async Task<IActionResult> Details(int id)
		{
			//Get product detail
			var product = await _client.GetAsync(new GetProductFeedbackById
			{
				ProductId = id
			});

			//Get deal product of week
			var dealProductOfWeeks = await _client.GetAsync(new GetDealProductOfWeek());

			var productDetail = new HomeViewModels
			{
				ProductDetail = product,
				ProductsOfWeek = dealProductOfWeeks
			};

			var sizeList = product.ProductSizes.OrderBy(x => x.Size.SizeType).Select
			(x => new SelectListItem { Value = Convert.ToString(x.Size.Id), Text = x.Size.SizeType }).ToList();
			ViewBag.SizeLists = sizeList;

			return View(productDetail);
		}

		[HttpPost]
		public async Task<IActionResult> AddComment(
			string name,
			string email,
			string number,
			double point,
			string message,
			int productId)
		{

			await _client.PostAsync(new Comment
			{
				Email = email,
				Message = message,
				Name = name,
				Phone = number,
				Point = point,
				ProductID = productId
			});
			return RedirectToAction("Details", new { id = productId });
		}

		public IActionResult Tracking()
		{
			return View();
		}
	}
}

SWP391.OnlineShop.Portal/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ServiceStack;
using SWP391.OnlineShop.Common.Constraints;
using SWP391.OnlineShop.Common.Enums;
using SWP391.OnlineShop.Common.Extensions;
using SWP391.OnlineShop.Core.Models.Identities;
using SWP391.OnlineShop.ServiceModel.ViewModels.Profiles;
using SWP391.OnlineShop.ServiceModel.ViewModels.Vouchers;
using System.Security.Claims;
using static SWP391.OnlineShop.ServiceModel.ServiceModels.AccountModels;
using static SWP391.OnlineShop.ServiceModel.ServiceModels.ProfileModels;

namespace SWP391.OnlineShop.Portal.Controllers
{
    [Authorize]
    public class ProfileController : BaseController
    {
        private readonly UserManager<User> _userManager;
        private readonly IJsonServiceClient _client;

        public ProfileController(
            UserManager<User> userManager,
            IJsonServiceClient client)
        {
            _userManager = userManager;
            _client = client;
        }

        #region Commons

        private bool CheckUserRequest(User userChange)
        {
            var emailUserRequest = User.Claims
                .FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;

            return emailUserRequest != null && emailUserRequest.Equals(userChange.Email);
        }

        #endregion

        public async Task<IActionResult> Index(int userId)
        {
            var user = await _userManager.FindByIdAsync(userId.ToString());
            var isCheckUser = CheckUserRequest(user);

            if (!isCheckUser)
            {
                return RedirectToAction("ErrorForbidden", "Account");
            }

            var generalViewModel = new GeneralViewModel
            {
                Id = user.Id.ToString(),
                DisplayEmail = user.Email,
                DisplayImage = user.Image,
                DisplayName = user.UserName,
                DisplayGender = user.Gender,
                DisplayPhoneNumber = user.PhoneNumber
            };

            // Voucher
            var vouchers = await _client.GetAsync(new GetUserVouchers
            {
                UserId = user.Id
            });

            // Address
            var addresses = await _client.GetAsync(new GetUserAddresses
            {
                UserId = user.Id
            });

            // Collaboration
            var requests = await _client.GetAsync(new GetUserRequests
            {
                UserId = user.Id
            });

            var profileVm = new ProfileViewModels
            {
                GeneralViewModel = generalViewModel,
                SecurityViewModel = new SecurityViewModel(),
                AddressViewModel = new AddressViewModels
                {
                    AddressViewModelList = addresses
                },
                VoucherViewModels = vouchers ?? new List<UserVoucherViewModel>(),
                RequestViewModel = new RequestViewModels
                {
                    RequestDataViewModels = requests
                }
            };

            // Request Tab
            var requestTabString = TempData["RequestTab"] as string ?? string.Empty;

            if (!string.IsNullOrEmpty(requestTabString))
            {
                var requestTab = requestTabString.ToEnum<ProfileTab>();
                profileVm.RequestTab = requestTab;
            }
            else
            {
                var requestTab = HttpContext.Session.GetString("RequestTab");
                if (!string.IsNullOrEmpty(requestTab))
                {
                    var requestTabSession = requestTab.ToEnum<ProfileTab>();
                    profileVm.RequestTab = requestTabSession;
                    HttpContext.Session.Remove("RequestTab");
                }
            }

            return View(profileVm);
        }

        #region General

        [HttpPost]
        public async Task<IActionResult> ChangeName(ProfileViewModels request)
        {
            var email = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
            var user = await _userManager.FindByEmailAsync(email);

            if (string.IsNullOrEmpty(request.GeneralViewModel.DisplayName.Trim()))
            {
                TempData["IsError"] = "true";
                TempData["ErrorMess"] = "Display name is empty or null. Please re-enter";
                return RedirectToAction(nameof(Index), new { userId = user.Id });
            }

            if (user.UserName.Equals(request.GeneralViewModel.DisplayName.Trim()))
            {
                TempData["IsError"] = "true";
                TempData["ErrorMess"] = "New display name input is similar with old one. Please re-enter";
                return RedirectToAction(nameof(Index), new { userId = user.Id });
            }

            var checkUser = await _userManager.FindByNameAsync(request.GeneralViewModel.DisplayName.Trim());
            if (checkUser == null)
            {
                var isUpdateName = await _client.PutAsync(new PutUpdateUserName
                {
                    UserId = user.Id,
                    NewName = request.GeneralViewModel.DisplayName.Trim()
                });

                if (isUpdateName.StatusCode != Common.Enums.StatusCode.Success)
                {
                    TempData["IsError"] = "true";
                    TempData["ErrorMess"] = $"{isUpdateName.ErrorMessage}. Please re-enter";
                    return RedirectToAction(nameof(Index), new { userId = user.Id });
                }

                TempData["SuccessMess"] = "Update display name success. Please double-check";
                return RedirectToAction(nameof(Index), new { userId = user.Id });
            }

            TempData["IsError"] = "true";
            TempData["ErrorMess"] = "This name already taken. Please re-enter";
            return RedirectToAction(nameof(Index), new { userId = user.Id });
        }

        [HttpPost]
        public async Task<IActionResult> ChangeEmail(ProfileViewModels request)
        {
            var email = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
            var user = await _userManager.FindByEmailAsync(email);

            if (string.IsNullOrEmpty(request.GeneralViewModel.DisplayEmail.Trim()))
            {
                TempData["IsError"] = "true";
                TempData["ErrorMess"] = "Display email is empty or null. Please re-enter";
                return RedirectToAction(nameof(Index), new { userId = user.Id });
            }

            if (!request.GeneralViewModel.DisplayEmail.IsEmail())
            {
                TempData["IsError"] = "true";
                TempData["ErrorMess"] = "Data input does not match with email template. Please re-enter";
                return RedirectToAction(nameof(Index), new { userId = user.Id });
            }

            var checkUser = await _userManager.FindByEmailAsync(request.GeneralViewModel.DisplayEmail.Trim());

            if (checkUser == null)
            {
                var isUpdateEmail = await _client.PutAsync(new PutUpdateUserEmail
                {
                    UserId = user.Id,
                    NewEmail = request.GeneralViewModel.DisplayEmail.Trim()
                });

                if (isUpdateEmail.StatusCode != Common.Enums.StatusCode.Success)
                {
                    TempData["IsError"] = "true";
                    TempData["ErrorMess"] = $"{isUpdateEmail.ErrorMessage}. Please re-enter";
                    return RedirectToAction(nameof(Index), new { userId = user.Id });
                }

                TempData["SuccessMess"] = "Update display email success. Please double-check";
                return RedirectToAction(nameof(Index), new { userId = user.Id });
            }

            TempData["IsError"] = "true";
            TempData["ErrorMess"] = "This email already taken. Please re-enter";
            return RedirectToAction(nameof(Index), new { userId = user.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangeAvatar(IFormFile? updateAvatar)
        {
            var email = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
            var user = await _userManager.FindByEmailAsync(email);

            if (updateAvatar == null)
            {
                TempData["IsError"] = "true";
                TempData["ErrorMess"] = "File update empty or null. Please re-enter";
                return RedirectToAction(nameof(Index), new { userId = user.Id });
            }

            var imageFolderLink = $"{Convert.ToString(Directory.GetCurrentDirectory())}\\wwwroot\\uploads\\users\\{user.Id}";
            if (!Directory.Exists(imageFolderLink))
            {
                Directory.CreateDirectory(imageFolderLink);
            }

            var avatarLink = Path.Combine(imageFolderLink, updateAvatar.FileName);

            await using Stream fileStream = new FileStream(avatarLink, FileMode.Create);
            await updateAvatar.CopyToAsync(fileStream);
            var imageLink = $"/uploads/users/{user.Id}/{updateAvatar.FileName}";

            var isUpdateName = await _client.PutAsync(new PutUpdateUserAvatar
            {
                UserId = user.Id,
                NewAvatar = imageLink
            });

            if (isUpdateName.StatusCode != Common.Enums.StatusCode.Success)
            {
                TempData["IsError"] = "true";
                TempData["ErrorMess"] = $"{isUpdateName.ErrorMessage}. Please re-enter";
                return RedirectToAction(nameof(Index), new { userId = user.Id });
            }

            TempData["SuccessMess"] = "Update avatar success. Please double-check";
            return RedirectToAction(nameof(Index), new { userId = user.Id });
        }

        [HttpPost]

SWP391.OnlineShop.Portal/Views/Shared/HomePartial/_HomeFooterPartial.cshtml
<!-- start footer Area -->
<footer class="footer-area section_gap" style="color: white">
    <div class="container">
        <div class="row">
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>About Us</h6>
                    <div style="font-size: .8rem">
                        <div>SHOPPING AND SELLING ONLINE IS SIMPLE, FAST AND SAFE. </div><br/>
                        <div>If you are looking for a website to buy and sell online then KARMA is a great choice for you. </div><br />
                        <div>KARMA is an e-commerce site that allows buyers and sellers to interact and easily exchange information about the shop's products and promotions.  </div><br />
                        <div>Therefore, buying and selling on KARMA becomes faster and simpler. You can chat directly with the seller to ask directly about the item you want to buy.  </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Newsletter</h6>
                    <p>Stay update with our latest</p>
                    <div class="" id="mc_embed_signup">

                        <form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                              method="get" class="form-inline">

                            <div class="d-flex flex-row">

                                <input class="form-control" name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '"
                                       required="" type="email">


                                <button class="click-btn btn btn-default"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></button>
                                <div style="position: absolute; left: -5000px;">
                                    <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                                </div>

                            </div>
                            <div class="info"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget mail-chimp">
                    <h6 class="mb-20">Instragram Feed</h6>
                    <ul class="instafeed d-flex flex-wrap">
                        <li><img src="~/template/img/i1.jpg" alt=""></li>
                        <li><img src="~/template/img/i2.jpg" alt=""></li>
                        <li><img src="~/template/img/i3.jpg" alt=""></li>
                        <li><img src="~/template/img/i4.jpg" alt=""></li>
                        <li><img src="~/template/img/i5.jpg" alt=""></li>
                        <li><img src="~/template/img/i6.jpg" alt=""></li>
                        <li><img src="~/template/img/i7.jpg" alt=""></li>
                        <li><img src="~/template/img/i8.jpg" alt=""></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Follow Us</h6>
                    <p>Let us be social</p>
                    <div class="footer-social d-flex align-items-center">
                        <a href="#"><i class="fa-brands fa-facebook"></i></a>
                        <a href="#"><i class="fa-brands fa-twitter"></i></a>
                        <a href="#"><i class="fa-brands fa-dribbble"></i></a>
                        <a href="#"><i class="fa-brands fa-behance"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
            <p class="footer-text m-0">
                Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved
            </p>
        </div>
    </div>
</footer>
<!-- End footer Area -->

SWP391.OnlineShop.Portal/Views/Shared/HomePartial/_HomeNavbarPartial.cshtml
@using System.Security.Claims
@using SWP391.OnlineShop.Common.Constraints
@{
    var roles = User.Claims.Where(c => c.Type == ClaimTypes.Role);
    var role = string.Join(CommonConstraints.JoinCharacter, roles.Select(x => x.Value));

    var id = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
}

<!-- Start Header Area -->
<header class="header_area sticky-header">
    <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light main_box">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <a class="navbar-brand logo_h" asp-action="Index" asp-controller="Home"><img src="~/template/img/logo.png" alt=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    <ul class="nav navbar-nav menu_nav ml-auto">
                        <li class="nav-item active"><a class="nav-link" asp-action="Index" asp-controller="Home">Home</a></li>
                        <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                               aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a asp-action="Index" asp-controller="Product" class="nav-link">Shop</a></li>
                                
                                @if (User.Identity is { IsAuthenticated: true })
                                {
                                    <li class="nav-item"><a asp-action="Index" asp-controller="Cart" class="nav-link">Shopping Cart</a></li>
                                    <li class="nav-item"><a asp-action="MyOrders" asp-controller="Cart" class="nav-link">My Orders</a></li>
                                    <li class="nav-item"><a asp-action="ReceiveVoucher" asp-controller="Voucher" class="nav-link">Receive Voucher</a></li>
                                }
                            </ul>
                        </li>
                        <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                               aria-expanded="false">Blog</a>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a asp-action="Index" asp-controller="Post" class="nav-link">Blog</a></li>
                            </ul>
                        </li>
                        <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                               aria-expanded="false">Users</a>
                            <ul class="dropdown-menu">
                                @if (User.Identity is { IsAuthenticated: true })
                                {
                                    <li class="nav-item"><a asp-action="Index" asp-controller="Profile" asp-route-userId="@id" class="nav-link">User Profile</a></li>
                                    <li class="nav-item"><a asp-action="Logout" asp-controller="Account" class="nav-link">Logout</a></li>
                                    @*<li class="nav-item"><a asp-action="Tracking" asp-controller="Product" class="nav-link">Tracking</a></li>*@

                                    @if (role.Contains(RoleConstraints.Admin))
                                    {
                                        @*<li class="nav-item"><a asp-action="Index" asp-controller="Element" class="nav-link">Elements</a></li>*@
                                    }
                                }
                                else
                                {
                                    <li class="nav-item"><a asp-action="Login" asp-controller="Account" class="nav-link">Login</a></li>
                                    <li class="nav-item"><a asp-action="Register" asp-controller="Account" class="nav-link">Register</a></li>
                                }
                            </ul>
                        </li>
                        @if (role.Contains(RoleConstraints.Admin))
                        {
                            <li class="nav-item"><a asp-action="Index" asp-controller="Dashboard" asp-area="Managements" class="nav-link">Managements</a></li>
                        }
                        <li class="nav-item"><a asp-action="Contact" asp-controller="Home" class="nav-link">Contact</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @*<li class="nav-item"><a href="#" class="cart"><span class="ti-bag"></span></a></li>*@
                        <li class="nav-item">
                            <button class="search"><span class="lnr lnr-magnifier" id="search"></span></button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="search_input" id="search_input_box">
        <div class="container">
            <form class="d-flex justify-content-between">
                <input type="text" class="form-control" id="search_input" placeholder="Search Here">
                <button type="submit" class="btn"></button>
                <span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
            </form>
        </div>
    </div>
</header>
<!-- End Header Area -->