SWP391.OnlineShop.Portal/Areas/Files/Controllers/FileManagerController.cs
using elFinder.NetCore;
using elFinder.NetCore.Drivers.FileSystem;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace SWP391.OnlineShop.Portal.Areas.Files.Controllers
{
    [Area("Files")]
    public class FileManagerController : Controller
    {
        private readonly IWebHostEnvironment _env;
        public FileManagerController(
            IWebHostEnvironment env)
        {
            _env = env;
        }

        [Route("/file-manager")]
        public IActionResult Index()
        {
            return View();
        }

        // Url để client-side kết nối đến backend
        // /el-finder-file-system/connector
        [Route("file-manager-connector")]
        public async Task<IActionResult> Connector()
        {
            var connector = GetConnector();
            return await connector.ProcessAsync(Request);
        }

        // Địa chỉ để truy vấn thumbnail
        // /el-finder-file-system/thumb
        [Route("file-manager-thumb/{hash}")]
        public async Task<IActionResult> Thumbs(string hash)
        {
            var connector = GetConnector();
            return await connector.GetThumbnailAsync(HttpContext.Request, HttpContext.Response, hash);
        }

        private Connector GetConnector()
        {
            // Thư mục gốc lưu trữ là wwwwroot/files (đảm bảo có tạo thư mục này)
            var pathRoot = "uploads";

            var driver = new FileSystemDriver();

            var absoluteUrl = UriHelper.BuildAbsolute(Request.Scheme, Request.Host);
            var uri = new Uri(absoluteUrl);

            // .. ... wwww/files
            var rootDirectory = Path.Combine(_env.WebRootPath, pathRoot);
            var url = $"{uri.Scheme}://{uri.Authority}/{pathRoot}/";
            var urlThumb = $"{uri.Scheme}://{uri.Authority}/file-manager-thumb/";


            var root = new RootVolume(rootDirectory, url, urlThumb)
            {
                IsLocked = false, // If locked, files and directories cannot be deleted, renamed or moved
                Alias = "Files", // Beautiful name given to the root/home folder
                MaxUploadSizeInKb = 102400, // Limit imposed to user uploaded file <= 10MB
                ThumbnailSize = 100,
                IsReadOnly = false,
                //UploadAllow = new[] { "application/pdf", "image/jpg", "image/png", "image/jpeg" },
                //LockedFolders = new List<string>(new string[] { "Folder1" }
            };

            driver.AddRoot(root);

            return new Connector(driver)
            {
                // This allows support for the "onlyMimes" option on the client.
                MimeDetect = MimeDetectOption.Internal
            };
        }
    }
}

SWP391.OnlineShop.Portal/Areas/Files/Views/FileManager/Index.cshtml
<div id="elfinder" class="h-100"></div>

<script type="text/javascript">
    // Documentation for client options:
    // https://github.com/Studio-42/elFinder/wiki/Client-configuration-options
    $(document).ready(function () {
        var myCommands = elFinder.prototype._options.commands;

        // Not yet implemented commands in elFinder.NetCore
        var disabled = ['callback', 'chmod', 'editor', 'netmount', 'ping', 'search', 'zipdl', 'help'];
        elFinder.prototype.i18.en.messages.TextArea = "Edit";

        $.each(disabled, function (i, cmd) {
            var idx;
            (idx = $.inArray(cmd, myCommands)) !== -1 && myCommands.splice(idx, 1);
        });

        var options = {
            baseUrl: "@Url.Content("~/lib/download/elfinder/")",
            url: "@Url.Action("Connector", "FileManager")",
            rememberLastDir: false,
            commands: myCommands,
            height: "100%",
            lang: 'en',
            uiOptions: {
                toolbar: [
                    ['back', 'forward'],
                    ['reload', 'getfile'],
                    ['home', 'up'],
                    ['mkdir', 'mkfile', 'upload'],
                    ['open', 'download'],
                    ['undo', 'redo'],
                    ['info'],
                    ['quicklook'],
                    ['copy', 'cut', 'paste'],
                    ['rm'],
                    ['duplicate', 'rename', 'edit'],
                    ['selectall', 'selectnone', 'selectinvert'],
                    ['view', 'sort']
                ]
            },
            //onlyMimes: ["image", "text/plain"] // Get files of requested mime types only
            lang: 'en',
        };
        $('#elfinder').elfinder(options).elfinder('instance');
    });
</script>