SWP391.OnlineShop.Portal/Areas/Managements/Controllers/OrderController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ServiceStack;
using SWP391.OnlineShop.Core.Models.Identities;
using SWP391.OnlineShop.ServiceInterface.Loggers;
using SWP391.OnlineShop.ServiceModel.ServiceModels;
using System.Security.Claims;
using static SWP391.OnlineShop.ServiceModel.ServiceModels.AddressModel;
using static SWP391.OnlineShop.ServiceModel.ServiceModels.OrderModels;

namespace SWP391.OnlineShop.Portal.Areas.Managements.Controllers
{
    public class OrderController : BaseController
    {
        private readonly UserManager<User> _userManager;
        private readonly ILoggerService _logger;
        private readonly IJsonServiceClient _client;

        public OrderController(
            UserManager<User> userManager,
            ILoggerService logger,
            IJsonServiceClient client)
        {
            _userManager = userManager;
            _logger = logger;
            _client = client;
        }
        public async Task<IActionResult> Index()
        {
            var email = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
            if (string.IsNullOrEmpty(email))
            {
                return RedirectToAction("Login", "Account");
            }
            var user = await _userManager.FindByEmailAsync(email);
            if (user == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var orders = await _client.GetAsync(new GetAllOrder());
            return View(orders);
        }

        public async Task<IActionResult> Details(int id)
        {
            var email = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
            if (string.IsNullOrEmpty(email))
            {
                return RedirectToAction("Login", "Account");
            }
            var user = await _userManager.FindByEmailAsync(email);
            if (user == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var order = await _client.GetAsync(new GetCartInfo()
            {
                Id = id
            });
            var productSlider = await _client.GetAsync(new GetAllProduct());

            order.CustomerPhone = user.PhoneNumber;

            if (string.IsNullOrEmpty(order.CustomerAddress))
            {
                var userAddress = await _client.GetAsync(new GetAddressByUser()
                {
                    Email = email
                });
                order.CustomerAddress = userAddress.FullAddress;
            }
            if (string.IsNullOrEmpty(order.CustomerEmail))
            {

                order.CustomerAddress = email;
            }
            order.Sliders = productSlider.Take(8).ToList();
            return View(order);
        }
    }
}

SWP391.OnlineShop.Portal/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ServiceStack;
using SWP391.OnlineShop.Common.Constraints;
using SWP391.OnlineShop.Common.Enums;
using SWP391.OnlineShop.Common.Extensions;
using SWP391.OnlineShop.Core.Models.Identities;
using SWP391.OnlineShop.ServiceModel.ViewModels.Profiles;
using SWP391.OnlineShop.ServiceModel.ViewModels.Vouchers;
using System.Security.Claims;
using static SWP391.OnlineShop.ServiceModel.ServiceModels.AccountModels;
using static SWP391.OnlineShop.ServiceModel.ServiceModels.ProfileModels;

namespace SWP391.OnlineShop.Portal.Controllers
{
    [Authorize]
    public class ProfileController : BaseController
    {
        private readonly UserManager<User> _userManager;
        private readonly IJsonServiceClient _client;

        public ProfileController(
            UserManager<User> userManager,
            IJsonServiceClient client)
        {
            _userManager = userManager;
            _client = client;
        }

        #region Commons

        private bool CheckUserRequest(User userChange)
        {
            var emailUserRequest = User.Claims
                .FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;

            return emailUserRequest != null && emailUserRequest.Equals(userChange.Email);
        }

        #endregion

        public async Task<IActionResult> Index(int userId)
        {
            var user = await _userManager.FindByIdAsync(userId.ToString());
            var isCheckUser = CheckUserRequest(user);

            if (!isCheckUser)
            {
                return RedirectToAction("ErrorForbidden", "Account");
            }

            var generalViewModel = new GeneralViewModel
            {
                Id = user.Id.ToString(),
                DisplayEmail = user.Email,
                DisplayImage = user.Image,
                DisplayName = user.UserName,
                DisplayGender = user.Gender,
                DisplayPhoneNumber = user.PhoneNumber
            };

            // Voucher
            var vouchers = await _client.GetAsync(new GetUserVouchers
            {
                UserId = user.Id
            });

            // Address
            var addresses = await _client.GetAsync(new GetUserAddresses
            {
                UserId = user.Id
            });

            // Collaboration
            var requests = await _client.GetAsync(new GetUserRequests
            {
                UserId = user.Id
            });

            var profileVm = new ProfileViewModels
            {
                GeneralViewModel = generalViewModel,
                SecurityViewModel = new SecurityViewModel(),
                AddressViewModel = new AddressViewModels
                {
                    AddressViewModelList = addresses
                },
                VoucherViewModels = vouchers ?? new List<UserVoucherViewModel>(),
                RequestViewModel = new RequestViewModels
                {
                    RequestDataViewModels = requests
                }
            };

            // Request Tab
            var requestTabString = TempData["RequestTab"] as string ?? string.Empty;

            if (!string.IsNullOrEmpty(requestTabString))
            {
                var requestTab = requestTabString.ToEnum<ProfileTab>();
                profileVm.RequestTab = requestTab;
            }
            else
            {
                var requestTab = HttpContext.Session.GetString("RequestTab");
                if (!string.IsNullOrEmpty(requestTab))
                {
                    var requestTabSession = requestTab.ToEnum<ProfileTab>();
                    profileVm.RequestTab = requestTabSession;
                    HttpContext.Session.Remove("RequestTab");
                }
            }

            return View(profileVm);
        }

        #region General

        [HttpPost]
        public async Task<IActionResult> ChangeName(ProfileViewModels request)
        {
            var email = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
            var user = await _userManager.FindByEmailAsync(email);

            if (string.IsNullOrEmpty(request.GeneralViewModel.DisplayName.Trim()))
            {
                TempData["IsError"] = "true";
                TempData["ErrorMess"] = "Display name is empty or null. Please re-enter";
                return RedirectToAction(nameof(Index), new { userId = user.Id });
            }

            if (user.UserName.Equals(request.GeneralViewModel.DisplayName.Trim()))
            {
                TempData["IsError"] = "true";
                TempData["ErrorMess"] = "New display name input is similar with old one. Please re-enter";
                return RedirectToAction(nameof(Index), new { userId = user.Id });
            }

            var checkUser = await _userManager.FindByNameAsync(request.GeneralViewModel.DisplayName.Trim());
            if (checkUser == null)
            {
                var isUpdateName = await _client.PutAsync(new PutUpdateUserName
                {
                    UserId = user.Id,
                    NewName = request.GeneralViewModel.DisplayName.Trim()
                });

                if (isUpdateName.StatusCode != Common.Enums.StatusCode.Success)
                {
                    TempData["IsError"] = "true";
                    TempData["ErrorMess"] = $"{isUpdateName.ErrorMessage}. Please re-enter";
                    return RedirectToAction(nameof(Index), new { userId = user.Id });
                }

                TempData["SuccessMess"] = "Update display name success. Please double-check";
                return RedirectToAction(nameof(Index), new { userId = user.Id });
            }

            TempData["IsError"] = "true";
            TempData["ErrorMess"] = "This name already taken. Please re-enter";
            return RedirectToAction(nameof(Index), new { userId = user.Id });
        }

        [HttpPost]
        public async Task<IActionResult> ChangeEmail(ProfileViewModels request)
        {
            var email = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
            var user = await _userManager.FindByEmailAsync(email);

            if (string.IsNullOrEmpty(request.GeneralViewModel.DisplayEmail.Trim()))
            {
                TempData["IsError"] = "true";
                TempData["ErrorMess"] = "Display email is empty or null. Please re-enter";
                return RedirectToAction(nameof(Index), new { userId = user.Id });
            }

            if (!request.GeneralViewModel.DisplayEmail.IsEmail())
            {
                TempData["IsError"] = "true";
                TempData["ErrorMess"] = "Data input does not match with email template. Please re-enter";
                return RedirectToAction(nameof(Index), new { userId = user.Id });
            }

            var checkUser = await _userManager.FindByEmailAsync(request.GeneralViewModel.DisplayEmail.Trim());

            if (checkUser == null)
            {
                var isUpdateEmail = await _client.PutAsync(new PutUpdateUserEmail
                {
                    UserId = user.Id,
                    NewEmail = request.GeneralViewModel.DisplayEmail.Trim()
                });

                if (isUpdateEmail.StatusCode != Common.Enums.StatusCode.Success)
                {
                    TempData["IsError"] = "true";
                    TempData["ErrorMess"] = $"{isUpdateEmail.ErrorMessage}. Please re-enter";
                    return RedirectToAction(nameof(Index), new { userId = user.Id });
                }

                TempData["SuccessMess"] = "Update display email success. Please double-check";
                return RedirectToAction(nameof(Index), new { userId = user.Id });
            }

            TempData["IsError"] = "true";
            TempData["ErrorMess"] = "This email already taken. Please re-enter";
            return RedirectToAction(nameof(Index), new { userId = user.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangeAvatar(IFormFile? updateAvatar)
        {
            var email = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
            var user = await _userManager.FindByEmailAsync(email);

            if (updateAvatar == null)
            {
                TempData["IsError"] = "true";
                TempData["ErrorMess"] = "File update empty or null. Please re-enter";
                return RedirectToAction(nameof(Index), new { userId = user.Id });
            }

            var imageFolderLink = $"{Convert.ToString(Directory.GetCurrentDirectory())}\\wwwroot\\uploads\\users\\{user.Id}";
            if (!Directory.Exists(imageFolderLink))
            {
                Directory.CreateDirectory(imageFolderLink);
            }

            var avatarLink = Path.Combine(imageFolderLink, updateAvatar.FileName);

            await using Stream fileStream = new FileStream(avatarLink, FileMode.Create);
            await updateAvatar.CopyToAsync(fileStream);
            var imageLink = $"/uploads/users/{user.Id}/{updateAvatar.FileName}";

            var isUpdateName = await _client.PutAsync(new PutUpdateUserAvatar
            {
                UserId = user.Id,
                NewAvatar = imageLink
            });

            if (isUpdateName.StatusCode != Common.Enums.StatusCode.Success)
            {
                TempData["IsError"] = "true";
                TempData["ErrorMess"] = $"{isUpdateName.ErrorMessage}. Please re-enter";
                return RedirectToAction(nameof(Index), new { userId = user.Id });
            }

            TempData["SuccessMess"] = "Update avatar success. Please double-check";
            return RedirectToAction(nameof(Index), new { userId = user.Id });
        }

        [HttpPost]

SWP391.OnlineShop.Portal/Controllers/VoucherController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ServiceStack;
using SWP391.OnlineShop.Core.Models.Identities;
using SWP391.OnlineShop.ServiceInterface.Loggers;
using System.Security.Claims;
using static SWP391.OnlineShop.ServiceModel.ServiceModels.OrderModels;
using static SWP391.OnlineShop.ServiceModel.ServiceModels.ProfileModels;
using static SWP391.OnlineShop.ServiceModel.ServiceModels.VoucherModels;

namespace SWP391.OnlineShop.Portal.Controllers
{
	public class VoucherController : BaseController
	{
		private readonly UserManager<User> _userManager;
		private readonly ILoggerService _logger;
		private readonly IJsonServiceClient _client;

		public VoucherController(
			UserManager<User> userManager,
			ILoggerService logger,
			IJsonServiceClient client)
		{
			_userManager = userManager;
			_logger = logger;
			_client = client;
		}
		public async Task<IActionResult> ReceiveVoucher()
		{
			var vouchers = await _client.GetAsync(new GetAllAvailableVoucher()
			{
			});
			return View(vouchers);
		}

		public async Task<IActionResult> SaveVoucher(int id)
		{
			if (id == 0)
			{
				return StatusCode(500, "Voucher Not Found");
			}
			var email = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
			if (string.IsNullOrEmpty(email))
			{
				return RedirectToAction("Login", "Account");
			}
			var user = await _userManager.FindByEmailAsync(email);
			if (user == null)
			{
				return RedirectToAction("Login", "Account");
			}
			var saveVoucher = await _client.PostAsync(new PostAddVoucherToUser()
			{
				UserId = user.Id,
				VoucherId = id
			});
			if(saveVoucher.StatusCode == Common.Enums.StatusCode.Success) {
				var updateAmount = await _client.PutAsync(new PutUpdateVoucherAmount()
				{
					Id = id
				});
				return Ok();
			}
			return StatusCode(500, "Add Failed");
		}

		public async Task<IActionResult> GetUserVoucher(string code, int orderId)
		{
            var email = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
            if (string.IsNullOrEmpty(email))
            {
                return RedirectToAction("Login", "Account");
            }
            var user = await _userManager.FindByEmailAsync(email);
            if (user == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var cartDetailOrders = await _client.GetAsync(new GetCartInfo
            {
                Id = orderId
            });
			if(cartDetailOrders.OrderVouchers.Any())
			{
				return StatusCode(500, "This order already apply a voucher");
			}
            var vouchers = await _client.GetAsync(new GetUserVouchers()
			{
				UserId = user.Id
			});
			foreach (var item in vouchers)
			{
				if(item.VoucherCode == code) {
					return Ok(item);
				}
			}
			return StatusCode(500,"Voucher Not Found OR Expired");
		}

		public async Task<IActionResult> AddVoucherToOrder(int voucherId,int orderId,decimal total)
		{
			var email = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
			if (string.IsNullOrEmpty(email))
			{
				return RedirectToAction("Login", "Account");
			}
			var user = await _userManager.FindByEmailAsync(email);
			if (user == null)
			{
				return RedirectToAction("Login", "Account");
			}
			var api = await _client.PutAsync(new PutUpdateCartToContact()
			{
				Id = orderId,
				OrderStatus = Core.Models.Enums.OrderStatus.InCartContact,
				TotalCost = total
			});
			var addVoucherOrder = await _client.PostAsync(new PostAddVoucherToOrder()
			{
				OrderId = orderId,
				VoucherId = voucherId
			});
			var deleteOrderVoucher = await _client.DeleteAsync(new DeleteUserVoucher()
			{
				VoucherId = voucherId,
				UserId = user.Id
			});
			return Ok();
		}
	}
}

SWP391.OnlineShop.Portal/Areas/Managements/Views/Shared/AdminPartial/_AdminFooterPartial.cshtml
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Karma Shop <script>document.write(new Date().getFullYear());</script></span>
        </div>
    </div>
</footer>

SWP391.OnlineShop.Portal/Areas/Managements/Views/Shared/AdminPartial/_AdminModalPartial.cshtml
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" asp-controller="Account" asp-action="Logout" asp-area="">Logout</a>
            </div>
        </div>
    </div>
</div>

SWP391.OnlineShop.Portal/Areas/Managements/Views/Shared/AdminPartial/_AdminSidebarPartial.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using SWP391.OnlineShop.Common.Constraints
@{
    var roles = User.Claims.Where(u => u.Type == ClaimTypes.Role);
    var userRole = string.Join(CommonConstraints.JoinCharacter, roles.Select(x => x.Value));
    var id = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
}
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center">
        <div class="sidebar-brand-icon rotate-n-15">
            @*<i class="fas fa-music"></i>*@
            <i class="fa-brands fa-shopify"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Karma <sup>Shop</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <li class="nav-item active">
        <a class="nav-link" asp-action="Index" asp-controller="Home" asp-area="">
            <i class="fa-solid fa-store"></i>
            <span>Back to Shop</span>
        </a>
    </li>

    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" asp-action="Index" asp-controller="Dashboard" asp-area="Managements">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
        </a>
    </li>

    @if (!string.IsNullOrEmpty(userRole) &&
    userRole.Contains(RoleConstraints.Admin))
    {
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
            <a class="nav-link" onclick="openWindow('Job')" style="cursor: pointer">
                <i class="fa-solid fa-screwdriver-wrench"></i>
                <span>Job Schedule</span>
            </a>
        </li>

        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
            <a class="nav-link" onclick="openWindow('File')" style="cursor: pointer">
                <i class="fa-regular fa-folder"></i>
                <span>Folder Management</span>
            </a>
        </li>
    }

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Management
    </div>

    <!-- Nav Item - User Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#collapseUser" data-bs-toggle="collapse" data-target="#collapseUser"
           aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-user"></i>
            <span>Accounts</span>
        </a>
        <div id="collapseUser" class="collapse" aria-labelledby="headingTwo" data-parent="#collapseUser">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Accounts:</h6>
                <a asp-action="Index" asp-controller="Profile" asp-area="" asp-route-userId="@id" class="collapse-item">Profile</a>

                @if (!string.IsNullOrEmpty(userRole) &&
                userRole.Contains(RoleConstraints.Admin))
                {
                    <a class="collapse-item" asp-area="Managements" asp-action="Index" asp-controller="Request">Requests</a>
                    <a class="collapse-item" asp-area="Managements" asp-action="Index" asp-controller="User">Users</a>
                }

                @if (!string.IsNullOrEmpty(userRole) &&
                userRole.Contains(RoleConstraints.Marketing) &&
                !userRole.Contains(RoleConstraints.Admin))
                {
                    <a class="collapse-item" asp-area="Managements" asp-action="ManageCustomer" asp-controller="Marketing">Customers</a>
                }
            </div>
        </div>
    </li>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#collapseComponents" data-bs-toggle="collapse" data-target="#collapseComponents"
           aria-expanded="true" aria-controls="collapseComponents">
            <i class="fa-solid fa-sliders"></i>
            <span>Components</span>
        </a>
        <div id="collapseComponents" class="collapse" aria-labelledby="headingTwo" data-parent="#collapseComponents">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Components:</h6>

                @if (!string.IsNullOrEmpty(userRole) && (
                userRole.Contains(RoleConstraints.Admin) ||
                userRole.Contains(RoleConstraints.Sale) ||
                userRole.Contains(RoleConstraints.SaleManager)))
                {
                    <a class="collapse-item" asp-area="Managements" asp-action="Index" asp-controller="Order">Orders</a>
                    <a class="collapse-item" asp-area="Managements" asp-action="Index" asp-controller="Voucher">Vouchers</a>
                    <a class="collapse-item" asp-area="Managements" asp-controller="Marketing" asp-action="Index">Products</a>
                    

                    if (userRole.Contains(RoleConstraints.Admin))
                    {
                        <a class="collapse-item" asp-area="Managements" asp-controller="Marketing" asp-action="ManagePost">Posts</a>
                    }
                }

                @if (!string.IsNullOrEmpty(userRole) &&
                userRole.Contains(RoleConstraints.Marketing) &&
                !userRole.Contains(RoleConstraints.Admin))
                {
                    <a class="collapse-item" asp-area="Managements" asp-controller="Marketing" asp-action="Index">Products</a>
                    <a class="collapse-item" asp-area="Managements" asp-controller="Marketing" asp-action="ManagePost">Posts</a>
                }

                @if (!string.IsNullOrEmpty(userRole) && userRole.Contains(RoleConstraints.Admin))
                {
                    @* <a class="collapse-item" asp-area="Managements" asp-action="ManageTag" asp-controller="Marketing">Tags</a> *@
                    <a class="collapse-item" asp-area="Managements" asp-controller="Marketing" asp-action="ManageSize">Sizes</a>
                    <a class="collapse-item" asp-area="Managements" asp-action="Index" asp-controller="Category">Categories</a>
                    <a class="collapse-item" asp-area="Managements" asp-controller="Marketing" asp-action="ManageFeedback">Comments</a>
                    <a class="collapse-item" asp-area="Managements" asp-action="Index" asp-controller="Contact">Contacts</a>
                    <a class="collapse-item">Other</a>
                }
            </div>
        </div>
    </li>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#collapseConfig" data-bs-toggle="collapse" data-target="#collapseConfig"
           aria-expanded="true" aria-controls="collapseConfig">
            <i class="fas fa-fw fa-cog"></i>
            <span>Settings</span>
        </a>
        <div id="collapseConfig" class="collapse" aria-labelledby="headingTwo" data-parent="#collapseConfig">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Configurations:</h6>

                @if (!string.IsNullOrEmpty(userRole) && (userRole.Contains(RoleConstraints.Admin) || userRole.Contains(RoleConstraints.Marketing)))
                {
                    <a class="collapse-item" asp-area="Managements" asp-controller="Marketing" asp-action="ManageSlider">Sliders</a>
                }
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>

<script>
    function openWindow(type) {
        if (type != undefined) {
            $.ajax({
                type: "GET",
                data: { type: type },
                url: '@Url.Action("ViewTab", "Dashboard", new { Area = "Managements" })',
                success: function(result) {
                    window.open(result.url, "", "width=1100,height=800");
                }
            });
        }
    }
</script>